var customerController = require("../controllers/customerController"),
  mongoose = require("mongoose");

exports.assign = function(router) {

  router.post("/add/customer", customerController.addCustomer);
  router.post("/customer/login", customerController.customerLogin);
  router.post("/customer/logout", customerController.customerLogout);
  router.get("/get/customers",customerController.getCustomers);
  router.post("/newloan",customerController.newLoan);
  // By customeraddress, autogenerated loanId,  Required: loanDemanded, Duration (In months)
  router.post("/getLoans",customerController.getLoansCustomer); // get only loggedin customer loans
  // customerAddress, loanId, loanAmount,duration, state
  router.post("/repay",customerController.repayLoan);
  // customerAddress Required: loanId, loanAmount  
  router.post("/admin/getLoans",customerController.getLoansAdmin);
  // customerAddress, loanId, loanAmount,duration, state
  router.post("/admin/approveLoan",customerController.approveLoan);
  // Required: By banker customerAddress, loanId, loanAmount, interestRate
  router.post("/admin/grantLoan",customerController.grantLoan);
  // By banker provide: customerAddress, loanId, loanAmount
  
};
